issues:
  max-issues-per-linter: 10
  max-same-issues: 10
linters:
  disable:
    - typecheck
  enable:
    - gocritic
    - govet
    - unused
    - gosimple
    - gocyclo
    - staticcheck
    - revive
    - gofmt
